package chioas

var OasVersion = "3.0.3"

const (
	root = "/"

	tagNameApplicationJson = "application/json"
	tagNameComponents      = "components"
	tagNameContact         = "contact"
	tagNameContent         = "content"
	tagNameDefault         = "default"
	tagNameDescription     = "description"
	tagNameEmail           = "email"
	tagNameEnum            = "enum"
	tagNameExample         = "example"
	tagNameExternalDocs    = "externalDocs"
	tagNameIn              = "in"
	tagNameInfo            = "info"
	tagNameItems           = "items"
	tagNameLicense         = "license"
	tagNameName            = "name"
	tagNameOpenApi         = "openapi"
	tagNameOperationId     = "operationId"
	tagNameParameters      = "parameters"
	tagNamePaths           = "paths"
	tagNameProperties      = "properties"
	tagNameRef             = "$ref"
	tagNameRequestBody     = "requestBody"
	tagNameRequired        = "required"
	tagNameResponses       = "responses"
	tagNameSchema          = "schema"
	tagNameSchemas         = "schemas"
	tagNameServers         = "servers"
	tagNameSummary         = "summary"
	tagNameTags            = "tags"
	tagNameTermsOfService  = "termsOfService"
	tagNameTitle           = "title"
	tagNameType            = "type"
	tagNameUrl             = "url"
	tagNameVersion         = "version"

	refPathSchemas = "#/" + tagNameComponents + "/" + tagNameSchemas + "/"

	tagValuePath        = "path"
	tagValueQuery       = "query"
	tagValueTypeObject  = "object"
	tagValueTypeArray   = "array"
	tagValueTypeString  = "string"
	tagValueTypeNull    = "null"
	tagValueTypeInteger = "integer"
	tagValueTypeNumber  = "number"
	tagValueTypeBoolean = "boolean"
)
